apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secure-observable-secret-store
  labels:
    app.kubernetes.io/name: secure-observable-api
    app.kubernetes.io/component: secret-store
spec:
  provider:
    vault:
      server: https://vault.secure-observable.svc:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: external-secrets-vault-token
          key: token
          namespace: external-secrets
