kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: secure-observable
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8081
        protocol: TCP
      - containerPort: 443
        hostPort: 8444
        protocol: TCP
