apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: secure-observable
  labels:
    app.kubernetes.io/name: secure-observable-api
    app.kubernetes.io/component: secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secure-observable-secret-store
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secure-observable/prod/app
        property: DATABASE_URL
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: secure-observable/prod/app
        property: JWT_ACCESS_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: secure-observable/prod/app
        property: JWT_REFRESH_SECRET
    - secretKey: REFRESH_TOKEN_PEPPER
      remoteRef:
        key: secure-observable/prod/app
        property: REFRESH_TOKEN_PEPPER
    - secretKey: OAUTH_STATE_SECRET
      remoteRef:
        key: secure-observable/prod/app
        property: OAUTH_STATE_SECRET
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secure-observable/prod/app
        property: REDIS_PASSWORD
