apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: secure-observable-api
  labels:
    app.kubernetes.io/name: secure-observable-api
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secure-observable-api
