apiVersion: v1
kind: Service
metadata:
  name: secure-observable-api-preview
  namespace: secure-observable
  labels:
    app.kubernetes.io/name: secure-observable-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: rollout
spec:
  selector:
    app.kubernetes.io/name: secure-observable-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
